version: "3.8"
services:
  dex-tracking:
    container_name: dex-tracking
    restart: unless-stopped
    image: node:lts
    working_dir: /usr/src/app
    command: node bot.js
    volumes:
      - "./:/usr/src/app"
